### ISSUE TITLE
[question]: Why was AsyncResult removed?

### ISSUE THREAD

**Issue by florian-obernberger** [higorlapa/result#10]
I think the title covers it pretty well but I will elaborate a bit further.

I am currently using version 3.1.0 of the package and was about to migrate to 4.0.0 when I realized, that the `AsyncResult` typedef along with its extensions was gone. I am heavily using this alias and its extension for a project of mine and just wanted to ask, why this feature was removed? Because in my opinion it does not conflict with the simplicity of the project.

I hope I did not come across as rude, I genuinely am just interested!

**Comment by higorlapa** [comment]
Hi! Thanks for asking. Cause it was just a type alias for `Future<Result>`, it is as simple as creating the `typedef` on your own project. Do you think it would work like this?

you could do: 

```dart
typedef AsyncResult<S, E> = Future<Result<S, E>>;
```

**Comment by florian-obernberger** [comment]
Yes that would work, but I'll probably also have to copy the extension methods (like the `mapError` and `map` functions) because I am also using them in a web api.

It's not that I cannot implement the extensions myself, I was just interested in your reasoning for it!

**Comment by higorlapa** [comment]
Got it. Feel free to reopen this issue or open another one if you need more help
