### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by rddewan** [higorlapa/result#11]
Hi,
How do we write test case for Result. I cant access the success or error  value in test case. It always fail in 
`expectLater(response.tryGetSuccess(), true);    `
```
test('Give login request When login Then return success', () async {
    
    when(mockSettingRepository.addToBox<String>(accessTokenKey,loginResponse.accessToken))
      .thenAnswer((_) async => true);

    when(mockLoginRepository.login(loginRequest))
      .thenAnswer((_) async => loginResponse);

    final loginService = LoginService(mockLoginRepository, mockSettingRepository);
    final Result<bool, Failure> response = await loginService.login(loginRequest);

    
    expect(response.isSuccess(), true);
    expectLater(response.tryGetSuccess(), true);    
    expect(response, isA<Result>());    
    verify(mockLoginRepository.login(loginRequest)).called(1);


  });
```

**Comment by higorlapa** [comment]
Why are you using `expectLater` in this case?  
If you use
```dart
    expect(response.tryGetSuccess(), true);    
```
it should pass

**Comment by higorlapa** [comment]
There are a few unit tests [here](https://github.com/higorlapa/result/blob/main/test/src/result_test.dart) that you can use as examples. Tell me if this helps, @rddewan

**Comment by rddewan** [comment]
@higorlapa thank you for your response it fails in both `expect` and `expectLater`.
Previously there was `getSuccess` it was working with it
![Screenshot 2566-03-10 at 7 11 12 PM](https://user-images.githubusercontent.com/13164167/224312873-4417e48a-dc71-4833-940c-48820671bb34.png)

**Comment by rddewan** [comment]
@higorlapa Thank you it's working , My mistake i forgot to add stub
