### ISSUE TITLE
An Unwrap method like in rust would be nice

### ISSUE THREAD

**Issue by LucaCoduriV** [higorlapa/result#13]
If we are sure that there is no error we have to do something like this:
```dart
final userResult =
        await _apiAuthService.login(email: email, password: password);

if (userResult case Error(:final error)) {
  // handle error
}
final user = userResult.tryGetSuccess()!;
```
But I think that it would be better with something like this:
```dart
final userResult =
        await _apiAuthService.login(email: email, password: password);

if (userResult case Error(:final error)) {
  // handle error
}
final user = userResult.unwrap();
```

**Comment by higorlapa** [comment]
Hi! Thanks for the suggestion. 

You can now use `getOrThrow` on `multiple_result: ^5.1.0`
It will get the success value if you sure of the outcome or throw an exception otherwise.

**Comment by higorlapa** [comment]
Closing this as completed.
