### ISSUE TITLE
Flip the types

### ISSUE THREAD

**Issue by ghost** [higorlapa/result#3]
Any chance of flipping the types to improve the readability?

Currently, it reads like "result of an exception". 

But when you flip the types to `Result<Expected, Error>` it becomes "result of something I expect".

**Comment by JoDeveloper** [comment]
> Any chance of flipping the types to improve the readability?
> 
> Currently, it reads like "result of an exception".
> 
> But when you flip the types to `Result<Expected, Error>` it becomes "result of something I expect".

https://github.com/higorlapa/result/pull/4#issue-1373945824

**Comment by higorlapa** [comment]
Hi! Sorry for the late response. It was hard to consider it since it's a break change, but it makes sense. I merged the #4 (thanks @JoDeveloper) and I will release a new version with it soon (you can use the version from git ref main for now)
